// This file has been automatically generated by Codiquest parser. Do not edit it by hand or your changes will be lost

export const levels = [
  {
    "page": "index"
  },
  {
    "page": "crear-un-nuevo-modulo",
    "title": "Crear un nuevo módulo"
  },
  {
    "page": "creando-nuestra-primera-pagina",
    "title": "Creando nuestra primera página"
  },
  {
    "page": "organizando-el-contenido-en-sub-carpetas-y-otro-ti",
    "title": "Organizando el contenido en sub carpetas y otro tipo de enlaces internos"
  },
  {
    "page": "que-sigue",
    "title": "¿Qué sigue?"
  }
];
