// This file has been automatically generated by Codiquest parser. Do not edit it by hand or your changes will be lost

export const levels = [
  {
    "page": "index"
  },
  {
    "page": "la-constante-questions",
    "title": "La constante questions"
  },
  {
    "page": "configurador",
    "title": "Configurador"
  },
  {
    "page": "anadiendo-todas-las-preguntas-a-los-niveles",
    "title": "Añadiendo todas las preguntas a los niveles"
  },
  {
    "page": "anadiendo-preguntas-manualmente",
    "title": "Añadiendo preguntas manualmente"
  },
  {
    "page": "anadiendo-todas-las-preguntas",
    "title": "Añadiendo todas las preguntas"
  },
  {
    "page": "que-sigue",
    "title": "¿Qué sigue?"
  }
];
