// This file has been automatically generated by Codiquest parser. Do not edit it by hand or your changes will be lost

export const levels = [
  {
    "page": "index"
  },
  {
    "page": "otro",
    "title": "Otro"
  }
];
