// This file has been automatically generated by Codiquest parser. Do not edit it by hand or your changes will be lost

export const levels = [
  {
    "page": "index"
  },
  {
    "page": "repaso-rapido-de-markdown",
    "title": "Repaso rápido de Markdown"
  },
  {
    "page": "creando-un-modulo-automatizado",
    "title": "Creando un módulo automatizado"
  },
  {
    "page": "recursos",
    "title": "Recursos"
  },
  {
    "page": "bloques-extendidos",
    "title": "Bloques extendidos"
  },
  {
    "page": "bloques-extendidos-notificaciones",
    "title": "Bloques extendidos - Notificaciones"
  },
  {
    "page": "bloques-extendidos-code",
    "title": "Bloques extendidos - Code"
  },
  {
    "page": "bloques-extendidos-file",
    "title": "Bloques extendidos - File"
  },
  {
    "page": "automatizacion-de-preguntas",
    "title": "Automatización de preguntas"
  },
  {
    "page": "recap",
    "title": "Recap"
  },
  {
    "page": "que-sigue",
    "title": "¿Qué sigue?"
  }
];
