// This file has been automatically generated by Codiquest parser. Do not edit it by hand or your changes will be lost

export const levels = [
  {
    "page": "index"
  },
  {
    "page": "componentes-code",
    "title": "Componentes - Code",
    "labels": [
      "Code",
      "Prisma",
      "X"
    ]
  },
  {
    "page": "componentes-alert",
    "title": "Componentes - Alert",
    "labels": []
  },
  {
    "page": "componentes-files",
    "title": "Componentes - Files",
    "labels": []
  },
  {
    "page": "componentes-message",
    "title": "Componentes - Message",
    "labels": []
  },
  {
    "page": "componentes-browser",
    "title": "Componentes - Browser",
    "labels": []
  },
  {
    "page": "componentes-modalimage",
    "title": "Componentes - ModalImage",
    "labels": []
  },
  {
    "page": "otros-componentes",
    "title": "Otros componentes",
    "labels": []
  },
  {
    "page": "templates",
    "title": "Templates",
    "labels": []
  },
  {
    "page": "template-page",
    "title": "Template - Page",
    "labels": []
  },
  {
    "page": "template-fillcode",
    "title": "Template - FillCode",
    "labels": []
  },
  {
    "page": "template-choose",
    "title": "Template - Choose",
    "labels": []
  },
  {
    "page": "que-sigue",
    "title": "¿Qué sigue?",
    "labels": []
  }
];
