// This file has been automatically generated by Codiquest parser. Do not edit it by hand or your changes will be lost

export const levels = [
  {
    "page": "index"
  },
  {
    "page": "componentes-code",
    "title": "Componentes - Code"
  },
  {
    "page": "componentes-alert",
    "title": "Componentes - Alert"
  },
  {
    "page": "componentes-files",
    "title": "Componentes - Files"
  },
  {
    "page": "componentes-message",
    "title": "Componentes - Message"
  },
  {
    "page": "componentes-browser",
    "title": "Componentes - Browser"
  },
  {
    "page": "componentes-modalimage",
    "title": "Componentes - ModalImage"
  },
  {
    "page": "otros-componentes",
    "title": "Otros componentes"
  },
  {
    "page": "templates",
    "title": "Templates"
  },
  {
    "page": "template-page",
    "title": "Template - Page"
  },
  {
    "page": "template-fillcode",
    "title": "Template - FillCode"
  },
  {
    "page": "template-choose",
    "title": "Template - Choose"
  },
  {
    "page": "que-sigue",
    "title": "¿Qué sigue?"
  }
];
